# Generated by Django 6.0 on 2025-12-28 13:54

import ICAIapp.models
import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICAIapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionattempt',
            name='session',
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', ICAIapp.models.CustomUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.CharField(blank=True, choices=[('JUNIOR_I', 'Junior I'), ('JUNIOR_II', 'Junior II'), ('MID_I', 'Mid I'), ('MID_II', 'Mid II'), ('SENIOR', 'Senior')], max_length=16, verbose_name='level'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, max_length=255, verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tech_stack',
            field=models.JSONField(blank=True, default=list, verbose_name='tech stack'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, error_messages={'unique': 'A user with that username already exists.'}, help_text='Optional. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, null=True, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
        migrations.DeleteModel(
            name='InterviewSession',
        ),
        migrations.DeleteModel(
            name='QuestionAttempt',
        ),
    ]
