# Generated by Django 6.0 on 2025-12-29 10:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICAIapp', '0002_remove_questionattempt_session_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=255, verbose_name='role')),
                ('position', models.CharField(max_length=255, verbose_name='position')),
                ('level', models.CharField(choices=[('JUNIOR_I', 'Junior I'), ('JUNIOR_II', 'Junior II'), ('MID_I', 'Mid I'), ('MID_II', 'Mid II'), ('SENIOR', 'Senior')], max_length=16, verbose_name='level')),
                ('tech_stack', models.JSONField(blank=True, default=list, verbose_name='tech stack')),
                ('fastapi_session_id', models.CharField(blank=True, db_index=True, max_length=128, verbose_name='fastapi session id')),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='CREATED', max_length=16, verbose_name='status')),
                ('overall_feedback', models.TextField(blank=True, verbose_name='overall feedback')),
                ('overall_score', models.IntegerField(blank=True, null=True, verbose_name='overall score')),
                ('overall_meta', models.JSONField(blank=True, default=dict, verbose_name='overall meta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='started at')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='ended at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_sessions', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='order')),
                ('question', models.TextField(verbose_name='question')),
                ('answer', models.TextField(blank=True, verbose_name='answer')),
                ('feedback', models.TextField(blank=True, verbose_name='feedback')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='score')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='meta')),
                ('asked_at', models.DateTimeField(auto_now_add=True, verbose_name='asked at')),
                ('answered_at', models.DateTimeField(blank=True, null=True, verbose_name='answered at')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='ICAIapp.interviewsession', verbose_name='session')),
            ],
            options={
                'ordering': ['order'],
                'indexes': [models.Index(fields=['session', 'order'], name='ICAIapp_int_session_997fbf_idx')],
                'constraints': [models.UniqueConstraint(fields=('session', 'order'), name='uniq_session_turn_order')],
            },
        ),
    ]
