# Generated by Django 6.0 on 2025-12-29 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICAIapp', '0003_interviewsession_interviewturn'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InterviewTurn',
            new_name='InterviewQuestion',
        ),
        migrations.AlterField(
            model_name='interviewquestion',
            name='session',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='questions',
                to='ICAIapp.interviewsession',
                verbose_name='session'
            ),
        ),
        migrations.RemoveIndex(
            model_name='interviewquestion',
            name='ICAIapp_int_session_997fbf_idx',
        ),
        migrations.AddIndex(
            model_name='interviewquestion',
            index=models.Index(fields=['session', 'order'], name='ICAIapp_int_session_80dbce_idx'),
        ),
        migrations.RemoveConstraint(
            model_name='interviewquestion',
            name='uniq_session_turn_order',
        ),
        migrations.AddConstraint(
            model_name='interviewquestion',
            constraint=models.UniqueConstraint(fields=('session', 'order'), name='uniq_session_question_order'),
        ),
    ]
