# Generated by Django 6.0 on 2025-12-29 10:30

import uuid

import django.db.models.deletion
from django.db import migrations, models


def generate_public_token():
    return uuid.uuid4().hex


class Migration(migrations.Migration):

    dependencies = [
        ("ICAIapp", "0003_interviewsession_interviewturn"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interviewsession",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interview_sessions",
                to="ICAIapp.user",
                verbose_name="user",
            ),
        ),
        migrations.AlterField(
            model_name="interviewsession",
            name="position",
            field=models.CharField(blank=True, max_length=255, verbose_name="position"),
        ),
        migrations.AddField(
            model_name="interviewsession",
            name="mode",
            field=models.CharField(
                choices=[
                    ("conversation", "Conversation"),
                    ("drilldown", "Drilldown"),
                    ("case", "Case"),
                    ("challenge", "Challenge"),
                    ("retrospective", "Retrospective"),
                ],
                default="conversation",
                max_length=32,
                verbose_name="mode",
            ),
        ),
        migrations.AddField(
            model_name="interviewsession",
            name="public_token",
            field=models.CharField(
                db_index=True,
                default=generate_public_token,
                max_length=64,
                verbose_name="public token",
            ),
        ),
        migrations.AddField(
            model_name="interviewsession",
            name="evaluated_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="evaluated at"),
        ),
    ]
