# Generated by Django 6.0 on 2025-12-29 15:30

import django.db.models.deletion
import secrets
from django.conf import settings
from django.db import migrations, models


def generate_tokens_for_existing_sessions(apps, schema_editor):
    """Generate unique tokens for existing InterviewSession records."""
    InterviewSession = apps.get_model('ICAIapp', 'InterviewSession')
    for session in InterviewSession.objects.all():
        if not session.public_token:
            session.public_token = secrets.token_hex(32)
            session.save(update_fields=['public_token'])


class Migration(migrations.Migration):

    dependencies = [
        ('ICAIapp', '0004_rename_interviewturn_to_interviewquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='claimed at'),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='public_token',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, null=True, verbose_name='public token'),
        ),
        migrations.RunPython(generate_tokens_for_existing_sessions, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='interviewsession',
            name='public_token',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, unique=True, verbose_name='public token'),
        ),
        migrations.AlterField(
            model_name='interviewsession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interview_sessions', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
