# Generated by Django 6.0 on 2025-12-29 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ICAIapp", "0004_interview_session_guest_and_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interviewsession",
            name="public_token",
            field=models.CharField(
                blank=True,
                null=True,
                db_index=True,
                max_length=64,
                verbose_name="public token",
            ),
        ),
    ]
